### ISSUE TITLE
PEExtraFiles and Scripts ZIP files are missing.

### ISSUE THREAD

**Issue by aztazt** [ServiceDudes/cMDT#2]
I can't do step 5 of the documentation since both files are not there :

> Installation
> To install the cMDT Module from the Powershell Gallery:
> 
> Make sure you have installed all prerequisites.
> Install the cMDT module (Install-Module cMDT)
> Create a source directory (Example: C:\Sources) If you use another driveletter and patch you need to edit the configuration file: (C:\Program Files\WindowsPowerShell\Modules\cMDT\1.0.0.6\Examples\Deploy_MDT_Server_ConfigurationData.psd1)
> Copy install.wim file from a Windows 10 media to C:\Sources and rename the file to install_1.0.0.0.wim
> Copy the Zip-files PEExtraFiles_1.0.0.0.zip and Scripts_1.0.0.0.zip from (C:\Program Files\WindowsPowerShell\Modules\cMDT\1.0.0.6\Sources) to the C:\Sources directory.
> Run Powershell ISE as Administrator and open the file: C:\Program Files\WindowsPowerShell\Modules\cMDT\1.0.0.6\Examples\Deploy_MDT_Server.ps1
> Press F5 to run the script. It will take approximately 30 min (Depending on internet capacity and virtualization hardware). The server will reboot ones during this process.

Any advice about that issue ?

Thank you.

**Comment by ulfvins** [comment]
You can find the files in the develop branch as of now: https://github.com/ServiceDudes/cMDT/tree/develop/src/Sources

We aim to fix this.

Br,

Richard

**Comment by ulfvins** [comment]
Sorry, moved them to the master branch: https://github.com/ServiceDudes/cMDT/tree/master/src/Sources

**Comment by aztazt** [comment]
Thanx a lot !
